"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { toast } from "sonner";
import {
  Calendar,
  PhoneOff,
  X,
  UserPlus,
  Loader2,
  CheckCircle2,
  Clock,
  MapPin,
  Link as LinkIcon,
} from "lucide-react";
import { format, addDays } from "date-fns";
import type { Contact } from "@/types/database";

interface QuickActionsProps {
  contact: Contact;
  onActionComplete: () => void;
  onNextContact: () => void;
}

const DURATION_OPTIONS = [
  { value: "15", label: "15 minutes" },
  { value: "30", label: "30 minutes" },
  { value: "45", label: "45 minutes" },
  { value: "60", label: "1 hour" },
  { value: "90", label: "1.5 hours" },
  { value: "120", label: "2 hours" },
];

// Generate time slots from 6 AM to 9 PM in 15 min increments
const generateTimeSlots = () => {
  const slots: { value: string; label: string }[] = [];
  for (let hour = 6; hour <= 21; hour++) {
    for (let min = 0; min < 60; min += 15) {
      const time = `${hour.toString().padStart(2, "0")}:${min.toString().padStart(2, "0")}`;
      const displayHour = hour > 12 ? hour - 12 : hour === 0 ? 12 : hour;
      const ampm = hour >= 12 ? "PM" : "AM";
      const label = `${displayHour}:${min.toString().padStart(2, "0")} ${ampm}`;
      slots.push({ value: time, label });
    }
  }
  return slots;
};

const TIME_SLOTS = generateTimeSlots();

export function QuickActions({ contact, onActionComplete, onNextContact }: QuickActionsProps) {
  const [isProcessing, setIsProcessing] = useState(false);
  const [showScheduleDialog, setShowScheduleDialog] = useState(false);
  const [showWrongNumberDialog, setShowWrongNumberDialog] = useState(false);
  const [showReferralDialog, setShowReferralDialog] = useState(false);
  const [phoneType, setPhoneType] = useState<"mobile" | "office">("mobile");
  const [referralData, setReferralData] = useState({
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    mobile: "",
    title: "",
    notes: "",
  });

  // Meeting scheduling state
  const tomorrow = addDays(new Date(), 1);
  const defaultDate = format(tomorrow, "yyyy-MM-dd");
  const [meetingTitle, setMeetingTitle] = useState(`Meeting with ${contact.first_name} ${contact.last_name || ""}`);
  const [meetingDate, setMeetingDate] = useState(defaultDate);
  const [meetingTime, setMeetingTime] = useState("10:00");
  const [meetingDuration, setMeetingDuration] = useState("30");
  const [meetingLocation, setMeetingLocation] = useState("");
  const [meetingDescription, setMeetingDescription] = useState("");
  const [createCalendarInvite, setCreateCalendarInvite] = useState(true);

  const handleScheduleMeeting = async () => {
    if (!meetingTitle.trim() || !meetingDate || !meetingTime) {
      toast.error("Please fill in all required fields");
      return;
    }

    setIsProcessing(true);
    try {
      const response = await fetch("/api/contacts/create-meeting-with-calendar", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contactId: contact.id,
          title: meetingTitle.trim(),
          date: meetingDate,
          time: meetingTime,
          duration: parseInt(meetingDuration),
          location: meetingLocation.trim() || undefined,
          meetingLink: undefined, // Auto-generated by Google Calendar
          description: meetingDescription.trim() || undefined,
          createCalendarInvite: createCalendarInvite,
        }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Failed to create meeting");

      if (data.calendar?.htmlLink) {
        toast.success("Meeting scheduled with Google Calendar invite!");
      } else {
        toast.success("Meeting scheduled! (Calendar invite may not be available)");
      }

      // Reset form
      setMeetingTitle(`Meeting with ${contact.first_name} ${contact.last_name || ""}`);
      setMeetingDate(defaultDate);
      setMeetingTime("10:00");
      setMeetingDuration("30");
      setMeetingLocation("");
      setMeetingDescription("");
      
      setShowScheduleDialog(false);
      onActionComplete();
      onNextContact();
    } catch (error: any) {
      toast.error(error.message || "Failed to schedule meeting");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleNoAnswer = async () => {
    setIsProcessing(true);
    try {
      const response = await fetch("/api/contacts/update-call-attempt", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contactId: contact.id }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error);

      toast.success("Call attempt recorded");
      onActionComplete();
      onNextContact();
    } catch (error: any) {
      toast.error(error.message || "Failed to update call attempt");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleWrongNumber = async () => {
    setIsProcessing(true);
    try {
      const response = await fetch("/api/contacts/mark-wrong-number", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contactId: contact.id,
          phoneType: phoneType,
        }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error);

      toast.success("Wrong number marked and removed");
      setShowWrongNumberDialog(false);
      onActionComplete();
      onNextContact();
    } catch (error: any) {
      toast.error(error.message || "Failed to mark wrong number");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleNotInterested = async () => {
    setIsProcessing(true);
    try {
      const response = await fetch("/api/contacts/mark-not-interested", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contactId: contact.id }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error);

      toast.success("Contact marked as not interested");
      onActionComplete();
      onNextContact();
    } catch (error: any) {
      toast.error(error.message || "Failed to mark as not interested");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleCreateReferral = async () => {
    if (!referralData.firstName.trim()) {
      toast.error("First name is required");
      return;
    }

    setIsProcessing(true);
    try {
      const response = await fetch("/api/contacts/create-referral", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sourceContactId: contact.id,
          ...referralData,
        }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error);

      toast.success("Referral contact created!");
      setShowReferralDialog(false);
      setReferralData({
        firstName: "",
        lastName: "",
        email: "",
        phone: "",
        mobile: "",
        title: "",
        notes: "",
      });
      onActionComplete();
    } catch (error: any) {
      toast.error(error.message || "Failed to create referral");
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <>
      <div className="grid grid-cols-2 gap-2 p-4 border-t bg-muted/30">
        <Button
          onClick={() => setShowScheduleDialog(true)}
          className="bg-green-600 hover:bg-green-700 text-white"
          disabled={isProcessing}
        >
          <Calendar className="h-4 w-4 mr-2" />
          Schedule Meeting
        </Button>
        <Button
          onClick={handleNoAnswer}
          variant="secondary"
          disabled={isProcessing}
        >
          <PhoneOff className="h-4 w-4 mr-2" />
          No Answer
        </Button>
        <Button
          onClick={() => setShowWrongNumberDialog(true)}
          variant="destructive"
          disabled={isProcessing}
        >
          <X className="h-4 w-4 mr-2" />
          Wrong Number
        </Button>
        <Button
          onClick={handleNotInterested}
          variant="outline"
          disabled={isProcessing}
        >
          <X className="h-4 w-4 mr-2" />
          Not Interested
        </Button>
        <Button
          onClick={() => setShowReferralDialog(true)}
          variant="outline"
          className="col-span-2"
          disabled={isProcessing}
        >
          <UserPlus className="h-4 w-4 mr-2" />
          Create Referral
        </Button>
      </div>

      {/* Schedule Meeting Dialog */}
      <Dialog open={showScheduleDialog} onOpenChange={setShowScheduleDialog}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Calendar className="h-5 w-5" />
              Schedule Meeting
            </DialogTitle>
            <DialogDescription>
              Schedule a meeting with {contact.first_name} {contact.last_name}
              {contact.company_name && ` from ${contact.company_name}`}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            {/* Title */}
            <div className="space-y-2">
              <Label htmlFor="meeting-title">Meeting Title *</Label>
              <Input
                id="meeting-title"
                value={meetingTitle}
                onChange={(e) => setMeetingTitle(e.target.value)}
                placeholder="Demo call, Discovery meeting, etc."
              />
            </div>

            {/* Date and Time */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="meeting-date">Date *</Label>
                <Input
                  id="meeting-date"
                  type="date"
                  value={meetingDate}
                  onChange={(e) => setMeetingDate(e.target.value)}
                  min={format(new Date(), "yyyy-MM-dd")}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="meeting-time">Time *</Label>
                <Select value={meetingTime} onValueChange={setMeetingTime}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="max-h-[200px]">
                    {TIME_SLOTS.map((slot) => (
                      <SelectItem key={slot.value} value={slot.value}>
                        {slot.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* Duration */}
            <div className="space-y-2">
              <Label htmlFor="meeting-duration" className="flex items-center gap-1">
                <Clock className="h-3 w-3" />
                Duration
              </Label>
              <Select value={meetingDuration} onValueChange={setMeetingDuration}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {DURATION_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Location */}
            <div className="space-y-2">
              <Label htmlFor="meeting-location" className="flex items-center gap-1">
                <MapPin className="h-3 w-3" />
                Location (Optional)
              </Label>
              <Input
                id="meeting-location"
                value={meetingLocation}
                onChange={(e) => setMeetingLocation(e.target.value)}
                placeholder="Office, Zoom, etc."
              />
            </div>

            {/* Meeting Link - Hidden, auto-generated by Google Calendar */}
            {/* Meeting link will be automatically generated when calendar invite is created */}

            {/* Description */}
            <div className="space-y-2">
              <Label htmlFor="meeting-description">Description (Optional)</Label>
              <Textarea
                id="meeting-description"
                value={meetingDescription}
                onChange={(e) => setMeetingDescription(e.target.value)}
                placeholder="Meeting agenda, topics to discuss..."
                rows={3}
              />
            </div>

            {/* Create Calendar Invite */}
            <div className="flex items-center space-x-2">
              <Checkbox
                id="create-calendar-invite"
                checked={createCalendarInvite}
                onCheckedChange={(checked) => setCreateCalendarInvite(checked === true)}
              />
              <Label
                htmlFor="create-calendar-invite"
                className="text-sm font-normal cursor-pointer"
              >
                Create Google Calendar invite
              </Label>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowScheduleDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleScheduleMeeting} disabled={isProcessing}>
              {isProcessing ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <CheckCircle2 className="h-4 w-4 mr-2" />
              )}
              Schedule Meeting
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Wrong Number Dialog */}
      <Dialog open={showWrongNumberDialog} onOpenChange={setShowWrongNumberDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Mark Wrong Number</DialogTitle>
            <DialogDescription>
              Which phone number was wrong?
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>Phone Type</Label>
              <select
                value={phoneType}
                onChange={(e) => setPhoneType(e.target.value as "mobile" | "office")}
                className="w-full rounded-md border border-input bg-background px-3 py-2"
              >
                <option value="mobile">Mobile ({contact.mobile || "N/A"})</option>
                <option value="office">Office ({contact.phone || "N/A"})</option>
              </select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowWrongNumberDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleWrongNumber} variant="destructive" disabled={isProcessing}>
              {isProcessing ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <X className="h-4 w-4 mr-2" />
              )}
              Mark Wrong Number
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Create Referral Dialog */}
      <Dialog open={showReferralDialog} onOpenChange={setShowReferralDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Create Referral Contact</DialogTitle>
            <DialogDescription>
              Create a new contact from {contact.company_name}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>First Name *</Label>
                <Input
                  value={referralData.firstName}
                  onChange={(e) =>
                    setReferralData({ ...referralData, firstName: e.target.value })
                  }
                  placeholder="John"
                />
              </div>
              <div className="space-y-2">
                <Label>Last Name</Label>
                <Input
                  value={referralData.lastName}
                  onChange={(e) =>
                    setReferralData({ ...referralData, lastName: e.target.value })
                  }
                  placeholder="Doe"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label>Email</Label>
              <Input
                type="email"
                value={referralData.email}
                onChange={(e) =>
                  setReferralData({ ...referralData, email: e.target.value })
                }
                placeholder="john@example.com"
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Mobile Phone</Label>
                <Input
                  value={referralData.mobile}
                  onChange={(e) =>
                    setReferralData({ ...referralData, mobile: e.target.value })
                  }
                  placeholder="+1234567890"
                />
              </div>
              <div className="space-y-2">
                <Label>Office Phone</Label>
                <Input
                  value={referralData.phone}
                  onChange={(e) =>
                    setReferralData({ ...referralData, phone: e.target.value })
                  }
                  placeholder="+1234567890"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label>Title</Label>
              <Input
                value={referralData.title}
                onChange={(e) =>
                  setReferralData({ ...referralData, title: e.target.value })
                }
                placeholder="VP of Sales"
              />
            </div>
            <div className="space-y-2">
              <Label>Notes</Label>
              <Textarea
                value={referralData.notes}
                onChange={(e) =>
                  setReferralData({ ...referralData, notes: e.target.value })
                }
                placeholder="Referred by..."
                rows={3}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowReferralDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleCreateReferral} disabled={isProcessing}>
              {isProcessing ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <UserPlus className="h-4 w-4 mr-2" />
              )}
              Create Contact
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
